export ASTRA_DB_ID=cebe2d61-55a5-4f0e-8ed6-04003f2ae3f6
export ASTRA_DB_REGION=us-east1
export ASTRA_DB_USERNAME=battle_user
export ASTRA_DB_KEYSPACE=battlestax
export ASTRA_DB_PASSWORD=battle_password1